import {
  InjectionToken,
} from '@angular/core';

import {
  DiscoveryState,
} from '../../domain/discovery/discovery-state';

import {
  ExplorationBalanceV1,
} from '../../domain/exploration/exploration-balance';

import {
  GalaxyLocator,
  type ProceduralLocator,
} from '../../domain/generation/procedural-locator';

import {
  type UniverseGenerationKey,
} from '../../domain/generation/universe-generation-key';

import {
  type DiscoveryPointsRepository,
  type DiscoveryRepository,
} from '../../domain/repository/genesis-repositories';

import {
  GenesisIndexedDb,
} from '../../data/local/indexed-db/genesis-indexed-db';

import {
  DexieDiscoveryPointsRepository,
} from '../../data/local/repository/dexie-discovery-points.repository';

import {
  DexieDiscoveryRepository,
  type ProceduralTargetSeedResolver,
} from '../../data/local/repository/dexie-discovery.repository';

import {
  DexieExternalGalaxySearchStateRepository,
} from '../../data/local/repository/dexie-external-galaxy-search-state.repository';

import {
  GalaxyScientificStateTransitionEngine,
  type GalaxyScientificStateTransitionActionValue,
  type GalaxyScientificStateTransitionResult,
} from '../../simulation/exploration/galaxy-scientific-state-transition-engine';

import {
  ProceduralTargetResolver,
} from '../../simulation/regeneration/procedural-target-resolver';

export interface CommittedGalaxyScientificKnowledgeTransition
  extends GalaxyScientificStateTransitionResult {

  readonly globalDiscoveryPointsBefore:
    bigint;

  readonly globalDiscoveryPointsAfter:
    bigint;
}

export interface GalaxyScientificKnowledgeRuntime {
  commit(
    generationKey:
      UniverseGenerationKey,

    galaxyIndex:
      bigint,

    action:
      GalaxyScientificStateTransitionActionValue,
  ): Promise<CommittedGalaxyScientificKnowledgeTransition>;
}

/**
 * Point-26.1 persistence boundary for explicit galaxy scientific milestones.
 *
 * The runtime re-reads both persisted GalaxyLocator state and global PD inside
 * one Dexie read/write transaction. The transition policy supplies the frozen
 * galaxy-only cost (250 PD for catalogue, 500 PD for confirmation). If either
 * the DiscoveryState write or PD write fails, Dexie rolls the whole transaction
 * back. Before the spend is committed it also checkpoints the cumulative
 * extragalactic-search opportunity high-water mark, so reducing the spendable
 * PD balance can never revoke already-earned search attempts.
 *
 * No sector, system, body, observation instrument, seed, PRNG draw or procedural
 * Ground Truth is generated by this action.
 */
export class DexieGalaxyScientificKnowledgeRuntime
  implements GalaxyScientificKnowledgeRuntime {

  private readonly searchStateRepository:
    DexieExternalGalaxySearchStateRepository;

  constructor(
    private readonly database:
      GenesisIndexedDb,

    private readonly pointsRepository:
      DiscoveryPointsRepository,

    private readonly discoveryRepository:
      DiscoveryRepository,

    searchStateRepository?:
      DexieExternalGalaxySearchStateRepository,
  ) {
    this.searchStateRepository =
      searchStateRepository ??
      new DexieExternalGalaxySearchStateRepository(
        database,
      );
  }

  async commit(
    generationKey:
      UniverseGenerationKey,

    galaxyIndex:
      bigint,

    action:
      GalaxyScientificStateTransitionActionValue,
  ): Promise<CommittedGalaxyScientificKnowledgeTransition> {

    await this
      .database
      .openDatabase();

    return this
      .database
      .transaction(
        'rw',
        this.database.universes,
        this.database.navigation,
        this.database.discoveries,
        this.database.progress,
        async () =>
          this.commitInsideTransaction(
            generationKey,
            galaxyIndex,
            action,
          ),
      );
  }

  private async commitInsideTransaction(
    generationKey:
      UniverseGenerationKey,

    galaxyIndex:
      bigint,

    action:
      GalaxyScientificStateTransitionActionValue,
  ): Promise<CommittedGalaxyScientificKnowledgeTransition> {

    const locator =
      new GalaxyLocator(
        galaxyIndex,
      );

    const persistedBefore =
      DiscoveryState
        .fromCode(
          (
            await this
              .discoveryRepository
              .getState(
                generationKey,
                locator,
              )
          ).code,
        );

    const transition =
      GalaxyScientificStateTransitionEngine
        .evaluate(
          persistedBefore,
          action,
        );

    const globalDiscoveryPointsBefore =
      await this
        .pointsRepository
        .getGlobalDiscoveryPoints(
          generationKey,
        );

    const externalSearchStateBefore =
      await this
        .searchStateRepository
        .getState(
          generationKey,
        );

    if (
      globalDiscoveryPointsBefore <
      transition.discoveryPointCost
    ) {
      throw new RangeError(
        `PD insuficientes para ${action === 'CATALOGUE' ? 'catalogar' : 'confirmar'} la galaxia: ${globalDiscoveryPointsBefore}/${transition.discoveryPointCost} PD.`,
      );
    }

    const globalDiscoveryPointsAfter =
      globalDiscoveryPointsBefore -
      transition.discoveryPointCost;

    const earnedSearchOpportunitiesBeforeSpend =
      globalDiscoveryPointsBefore /
      ExplorationBalanceV1
        .externalGalaxySearchDiscoveryPointStep;

    const earnedSearchOpportunitiesHighWatermark =
      maxBigInt(
        earnedSearchOpportunitiesBeforeSpend,
        externalSearchStateBefore
          .earnedSearchOpportunitiesHighWatermark,
        externalSearchStateBefore
          .consumedSearchOpportunities,
        externalSearchStateBefore
          .lastAnnouncedEarnedSearchOpportunities,
      );

    await this
      .discoveryRepository
      .setState(
        generationKey,
        locator,
        transition.stateAfter,
      );

    await this
      .pointsRepository
      .setGlobalDiscoveryPoints(
        generationKey,
        globalDiscoveryPointsAfter,
      );

    await this
      .searchStateRepository
      .setState(
        generationKey,
        {
          ...externalSearchStateBefore,
          earnedSearchOpportunitiesHighWatermark,
        },
      );

    return Object.freeze({
      ...transition,
      globalDiscoveryPointsBefore,
      globalDiscoveryPointsAfter,
    });
  }
}

function maxBigInt(
  ...values:
    readonly bigint[]
): bigint {

  let maximum =
    0n;

  for (
    const value
    of values
  ) {
    if (
      value >
      maximum
    ) {
      maximum =
        value;
    }
  }

  return maximum;
}

const TARGET_SEED_RESOLVER:
  ProceduralTargetSeedResolver =
  Object.freeze({
    resolveTargetSeedNormalized(
      generationKey:
        UniverseGenerationKey,

      locator:
        ProceduralLocator,
    ): string {

      return ProceduralTargetResolver
        .resolveTargetSeed(
          generationKey,
          locator,
        )
        .normalizedValue;
    },
  });

export const GALAXY_SCIENTIFIC_KNOWLEDGE_RUNTIME =
  new InjectionToken<GalaxyScientificKnowledgeRuntime>(
    'GALAXY_SCIENTIFIC_KNOWLEDGE_RUNTIME',
    {
      providedIn:
        'root',

      factory:
        createGalaxyScientificKnowledgeRuntime,
    },
  );

function createGalaxyScientificKnowledgeRuntime():
  GalaxyScientificKnowledgeRuntime {

  const database =
    new GenesisIndexedDb();

  return new DexieGalaxyScientificKnowledgeRuntime(
    database,
    new DexieDiscoveryPointsRepository(
      database,
    ),
    new DexieDiscoveryRepository(
      database,
      TARGET_SEED_RESOLVER,
    ),
  );
}
