import { type StellarSystemLaboratoryFamily } from './stellar-system-laboratory-fixtures';
import {
  laboratoryBinarySemiMajorAxisAu,
  laboratoryOrbitalSpacingProfile,
  laboratoryProtectedSingleExtentAu,
} from './stellar-system-laboratory-orbital-spacing';

import {
  projectSystemSceneMotionContributions,
} from '../../system/system-scene-motion-projection';

import {
  buildLinearFitSystemScale,
} from '../../system/system-scene-scale-projection';

import {
  type SystemSceneBodySnapshot,
  type SystemSceneHabitableZoneSnapshot,
  type SystemSceneMotionContributionSnapshot,
  type SystemSceneOrbitalMotionSnapshot,
  type SystemSceneOrbitSnapshot,
  type SystemSceneSnapshot,
} from '../../system/system-scene-snapshot';

import {
  systemSceneMoonPresentationTimeScale,
} from '../../system/system-scene-secondary-motion';

/**
 * LABORATORY ONLY: actual binary fixture assembly from two complete SINGLE
 * systems already generated by the existing production engines. All source
 * stars, planets, moons, belts, comets and circumstellar HZ remain attached
 * to their original host. No P-type planetary materializer or visual body
 * redistribution is used. The mutual 3-body stability is NOT solved here.
 */
const LOCAL_SYSTEM_RADIUS_SCENE = 2.15;
const LOCAL_MINOR_ORBIT_LIMIT_SCENE = 2.38;

// All cadence changes belong to this QA composition, never to the generators
// or the authoritative orbital periods. Inner orbits must not race at zoom.
export const LAB_BINARY_ORBIT_SECONDS_PER_REVOLUTION = 300;
export const LAB_PLANET_MIN_ORBIT_SECONDS = 100;
export const LAB_MOON_MIN_ORBIT_SECONDS = 42;
export const LAB_MINOR_BODY_MIN_ORBIT_SECONDS = 90;

interface LaboratoryHost {
  readonly label: 'A' | 'B';
  readonly source: SystemSceneSnapshot;
  readonly scale: number;
  readonly anchor: SystemSceneMotionContributionSnapshot;
}

export function composeLaboratoryBinaryScene(
  singleA: SystemSceneSnapshot,
  singleB: SystemSceneSnapshot,
  family: StellarSystemLaboratoryFamily,
  massesSolar: readonly [number, number],
): SystemSceneSnapshot {
  if (singleA.multiplicityName !== 'SINGLE' || singleA.stars.length !== 1 ||
      singleB.multiplicityName !== 'SINGLE' || singleB.stars.length !== 1) {
    throw new RangeError('Binary laboratory assembly requires two COMPLETE SINGLE sources.');
  }
  const [massA, massB] = massesSolar;
  if (!Number.isFinite(massA) || !Number.isFinite(massB) || massA <= 0 || massB <= 0) {
    throw new RangeError('Both source-star masses must come from the catalogued SINGLE cards.');
  }

  // Select separation from BOTH actual, complete source populations before
  // composing the hierarchy. No planets are cut/reassigned, and no global
  // system generator is changed. Compact inputs can yield compact binaries;
  // an extended planetary system still requires a wider binary.
  const spacing = laboratoryOrbitalSpacingProfile(family.id);
  const binaryEccentricity = 0.12;
  const semiMajorAxisAu = laboratoryBinarySemiMajorAxisAu(
    laboratoryProtectedSingleExtentAu(singleA),
    laboratoryProtectedSingleExtentAu(singleB),
    massA,
    massB,
    binaryEccentricity,
    spacing.safetyFactor,
  );
  const relativeMotion: SystemSceneOrbitalMotionSnapshot = Object.freeze({
    id: 'lab-binary-relative',
    semiMajorAxisAu,
    eccentricity: binaryEccentricity,
    periodDays: 365.25 * Math.sqrt(semiMajorAxisAu ** 3 / (massA + massB)),
    rotationDegrees: 24,
    inclinationDegrees: 18,
    epochMeanAnomalyDegrees: 0,
  });
  const relativeScenePerAu = spacing.innerDisplayPeriastronScene /
    (relativeMotion.semiMajorAxisAu * (1 - relativeMotion.eccentricity));
  const playbackDaysPerRealSecond = singleA.simulation.playbackDaysPerRealSecond;
  const binaryTimeScale = relativeMotion.periodDays /
    (playbackDaysPerRealSecond * LAB_BINARY_ORBIT_SECONDS_PER_REVOLUTION);
  const anchorFor = (weight: number): SystemSceneMotionContributionSnapshot =>
    Object.freeze({
      motionId: relativeMotion.id,
      scale: weight,
      linearScenePerAu: relativeScenePerAu,
      presentationTimeScale: binaryTimeScale,
    });
  const hosts: readonly LaboratoryHost[] = Object.freeze([
    Object.freeze({
      label: 'A' as const,
      source: singleA,
      scale: LOCAL_SYSTEM_RADIUS_SCENE / localReferenceRadius(singleA),
      anchor: anchorFor(-massB / (massA + massB)),
    }),
    Object.freeze({
      label: 'B' as const,
      source: singleB,
      scale: LOCAL_SYSTEM_RADIUS_SCENE / localReferenceRadius(singleB),
      anchor: anchorFor(massA / (massA + massB)),
    }),
  ]);

  const outerSeparation = relativeMotion.semiMajorAxisAu *
    (1 + relativeMotion.eccentricity) * relativeScenePerAu;
  const globalRadius = Math.max(
    ...hosts.map(host =>
      Math.abs(host.anchor.scale) * outerSeparation + LOCAL_MINOR_ORBIT_LIMIT_SCENE,
    ),
  ) + 0.35;
  const scale = buildLinearFitSystemScale(
    relativeMotion.semiMajorAxisAu,
    globalRadius,
  );
  const motions: SystemSceneOrbitalMotionSnapshot[] = [relativeMotion];
  const orbits: SystemSceneOrbitSnapshot[] = [];
  const stars: SystemSceneBodySnapshot[] = [];
  const planets: SystemSceneBodySnapshot[] = [];
  const moons: SystemSceneSnapshot['moons'][number][] = [];
  const minorBodies: SystemSceneSnapshot['minorBodies'][number][] = [];
  const belts: NonNullable<SystemSceneSnapshot['asteroidBelts']>[number][] = [];
  const riskTargets: SystemSceneSnapshot['orbitalRiskTargets'][number][] = [];
  const zones: SystemSceneHabitableZoneSnapshot[] = [];

  for (const host of hosts) {
    const prefix = `lab-${host.label.toLowerCase()}-`;
    const motionId = (id: string): string => `${prefix}${id}`;
    const orbitId = (id: string): string => `${prefix}${id}`;
    // Source system IDs such as star-a, planet-0 and moon-0-0 are only unique
    // within one SINGLE. Namespace every body and cross-reference by host.
    const bodyId = (id: string): string => `${prefix}${id}`;
    const motionById = new Map(host.source.motions.map(motion => [motion.id, motion]));
    const orbitalGuideByMotion = new Map(
      host.source.orbits.filter(orbit => orbit.motionId !== null)
        .map(orbit => [orbit.motionId!, orbit]),
    );
    const linearPerAuByMotion = new Map<string, number>();

    for (const motion of host.source.motions) {
      const guide = orbitalGuideByMotion.get(motion.id);
      const originalSemiMajorScene = guide?.semiMajorScene ??
        motion.semiMajorAxisAu * host.source.scale.orbitScaleScenePerAu;
      const isMinorOrbit = guide?.kind === 'minor-body';
      const projectedSemiMajorScene = originalSemiMajorScene * host.scale;
      const semiMajorScene = isMinorOrbit
        ? Math.min(
            projectedSemiMajorScene,
            LOCAL_MINOR_ORBIT_LIMIT_SCENE / (1 + motion.eccentricity),
          )
        : projectedSemiMajorScene;
      const weight = Math.abs(guide?.motionScale ?? 1);
      linearPerAuByMotion.set(
        motion.id,
        semiMajorScene / (motion.semiMajorAxisAu * (weight || 1)),
      );
      motions.push(Object.freeze({ ...motion, id: motionId(motion.id) }));
    }

    const contributions = (
      source: readonly SystemSceneMotionContributionSnapshot[],
    ): readonly SystemSceneMotionContributionSnapshot[] => Object.freeze([
      host.anchor,
      ...source.map(contribution => {
        const localMotion = motionById.get(contribution.motionId);
        const isMoon = contribution.motionId.startsWith('moon-');
        const isPlanet = contribution.motionId.startsWith('planet-');
        const existingScale = isMoon && localMotion !== undefined
          ? Math.min(
              contribution.presentationTimeScale ?? 1,
              systemSceneMoonPresentationTimeScale(
                localMotion.periodDays,
                playbackDaysPerRealSecond,
              ),
            )
          : contribution.presentationTimeScale ?? 1;
        const minimumOrbitSeconds = isMoon
          ? LAB_MOON_MIN_ORBIT_SECONDS
          : isPlanet
            ? LAB_PLANET_MIN_ORBIT_SECONDS
            : LAB_MINOR_BODY_MIN_ORBIT_SECONDS;
        const presentationTimeScale = localMotion === undefined
          ? existingScale
          : Math.min(
              existingScale,
              localMotion.periodDays /
                (playbackDaysPerRealSecond * minimumOrbitSeconds),
            );
        return Object.freeze({
          motionId: motionId(contribution.motionId),
          scale: contribution.scale,
          linearScenePerAu: linearPerAuByMotion.get(contribution.motionId) ??
            contribution.linearScenePerAu ??
            host.source.scale.orbitScaleScenePerAu * host.scale,
          presentationTimeScale,
        });
      }),
    ]);
    const position = (parts: readonly SystemSceneMotionContributionSnapshot[]) =>
      Object.freeze(projectSystemSceneMotionContributions(
        parts,
        id => motions.find(motion => motion.id === id),
        0,
        scale,
      ));

    const ownStar = host.source.stars[0]!;
    const ownStarMotion = Object.freeze([host.anchor]);
    // An empty planetary group can have a very small reference radius. Keep
    // the canonical star's colour/luminosity/identity and a bounded display
    // radius instead of scaling it into a giant sphere in that case.
    const starRadiusScene = Math.min(0.24, Math.max(0.075, ownStar.radiusScene * host.scale));
    stars.push(Object.freeze({
      ...ownStar,
      id: bodyId(ownStar.id),
      label: host.label,
      title: `${ownStar.title} · estrella ${host.label}`,
      orbitId: `lab-orbit-star-${host.label.toLowerCase()}`,
      motionContributions: ownStarMotion,
      position: position(ownStarMotion),
      radiusScene: starRadiusScene,
      opticalRadiusScene: Math.max(starRadiusScene, Math.min(
        0.30,
        (ownStar.opticalRadiusScene ?? ownStar.radiusScene) * host.scale,
      )),
    }));

    const starOrbitalRadius = Math.abs(host.anchor.scale) *
      relativeMotion.semiMajorAxisAu * relativeScenePerAu;
    orbits.push(Object.freeze({
      id: `lab-orbit-star-${host.label.toLowerCase()}`,
      kind: 'stellar',
      label: `Órbita estelar ${host.label}`,
      colorHex: '#D7A46A',
      opacity: 0.37,
      semiMajorScene: starOrbitalRadius,
      semiMinorScene: starOrbitalRadius * Math.sqrt(1 - relativeMotion.eccentricity ** 2),
      focusOffsetScene: starOrbitalRadius * relativeMotion.eccentricity,
      rotationDegrees: relativeMotion.rotationDegrees,
      inclinationDegrees: relativeMotion.inclinationDegrees,
      motionId: relativeMotion.id,
      motionScale: host.anchor.scale,
      linearScenePerAu: relativeScenePerAu,
      anchorMotionContributions: Object.freeze([]),
    }));

    for (const orbit of host.source.orbits) {
      const motion = orbit.motionId === null ? undefined : motionById.get(orbit.motionId);
      const linear = orbit.motionId === null ? undefined : linearPerAuByMotion.get(orbit.motionId);
      const adjustedSemiMajor = motion !== undefined && linear !== undefined
        ? motion.semiMajorAxisAu * Math.abs(orbit.motionScale) * linear
        : orbit.semiMajorScene * host.scale;
      orbits.push(Object.freeze({
        ...orbit,
        id: orbitId(orbit.id),
        label: `${host.label} · ${orbit.label}`,
        semiMajorScene: adjustedSemiMajor,
        semiMinorScene: adjustedSemiMajor *
          (orbit.semiMajorScene > 0 ? orbit.semiMinorScene / orbit.semiMajorScene : 1),
        focusOffsetScene: adjustedSemiMajor *
          (orbit.semiMajorScene > 0 ? orbit.focusOffsetScene / orbit.semiMajorScene : 0),
        motionId: orbit.motionId === null ? null : motionId(orbit.motionId),
        anchorMotionContributions: contributions(orbit.anchorMotionContributions),
        ...(linear === undefined ? { linearScenePerAu: undefined } : { linearScenePerAu: linear }),
        postProjectionScale: undefined,
      }));
    }

    for (const planet of host.source.planets) {
      const parts = contributions(planet.motionContributions);
      planets.push(Object.freeze({
        ...planet,
        id: bodyId(planet.id),
        label: `${host.label} · ${planet.label}`,
        title: `${host.label} · ${planet.title}`,
        orbitId: planet.orbitId === null ? null : orbitId(planet.orbitId),
        radiusScene: planet.radiusScene * host.scale,
        position: position(parts),
        motionContributions: parts,
      }));
    }

    for (const moon of host.source.moons) {
      const parts = contributions(moon.motionContributions);
      moons.push(Object.freeze({
        ...moon,
        id: bodyId(moon.id),
        hostPlanetId: bodyId(moon.hostPlanetId),
        label: `${host.label} · ${moon.label}`,
        title: `${host.label} · ${moon.title}`,
        orbitId: orbitId(moon.orbitId),
        radiusScene: moon.radiusScene * host.scale,
        position: position(parts),
        motionContributions: parts,
        visualPresentation: Object.freeze({
          ...moon.visualPresentation,
          presentationRadiusScene: moon.visualPresentation.presentationRadiusScene * host.scale,
        }),
      }));
    }

    for (const minor of host.source.minorBodies) {
      const parts = contributions(minor.motionContributions);
      minorBodies.push(Object.freeze({
        ...minor,
        id: bodyId(minor.id),
        label: `${host.label} · ${minor.label}`,
        title: `${host.label} · ${minor.title}`,
        orbitId: orbitId(minor.orbitId),
        radiusScene: minor.radiusScene * host.scale,
        position: position(parts),
        motionContributions: parts,
      }));
    }

    if (host.source.habitableZone !== null) {
      const zone = host.source.habitableZone;
      zones.push(Object.freeze({
        ...zone,
        // These are the original SINGLE's HZ physical AU edges and topology.
        // Only presentation radii are scaled with that same host's orbits.
        radiativeInnerRadiusScene: zone.radiativeInnerRadiusScene * host.scale,
        radiativeOuterRadiusScene: zone.radiativeOuterRadiusScene * host.scale,
        dynamicallyHabitableInnerRadiusScene: zone.dynamicallyHabitableInnerRadiusScene === null
          ? null : zone.dynamicallyHabitableInnerRadiusScene * host.scale,
        dynamicallyHabitableOuterRadiusScene: zone.dynamicallyHabitableOuterRadiusScene === null
          ? null : zone.dynamicallyHabitableOuterRadiusScene * host.scale,
        anchorMotionContributions: Object.freeze([host.anchor]),
      }));
    }

    for (const belt of host.source.asteroidBelts ?? []) {
      belts.push(Object.freeze({
        ...belt,
        id: bodyId(belt.id),
        label: `${host.label} · ${belt.label}`,
        innerRadiusScene: belt.innerRadiusScene * host.scale,
        outerRadiusScene: belt.outerRadiusScene * host.scale,
        peakRadiusScene: belt.peakRadiusScene === null ? null : belt.peakRadiusScene * host.scale,
        anchorMotionContributions: contributions(belt.anchorMotionContributions),
      }));
    }

    for (const risk of host.source.orbitalRiskTargets) {
      riskTargets.push(Object.freeze({
        ...risk,
        id: bodyId(risk.id),
        targetBodyId: bodyId(risk.targetBodyId),
        targetOrbitId: orbitId(risk.targetOrbitId),
        targetLabel: `${host.label} · ${risk.targetLabel}`,
      }));
    }
  }

  const availableRisks = riskTargets.filter(risk => risk.severity !== 'CROSSING');
  const crossingRisks = riskTargets.filter(risk => risk.severity === 'CROSSING');
  const composite: SystemSceneSnapshot = Object.freeze({
    ...singleA,
    address: Object.freeze({
      galaxyIndex: family.locator.galaxyIndex.toString(),
      sectorKey: family.locator.sectorKey.toString(),
      galacticObjectIndex: family.locator.galacticObjectIndex.toString(),
    }),
    proceduralIdentity: `LAB-BINARY-${family.systemSeedHex}-${singleA.proceduralIdentity}-${singleB.proceduralIdentity}`,
    title: `Binario de dos sistemas simples · familia ${family.id}`,
    multiplicityName: 'BINARY',
    componentCount: 2,
    accessibleLabel: 'Dos sistemas simples generados por separado, con estrellas, planetas, lunas y dos zonas habitables de origen, orbitando en torno al baricentro común. La estabilidad mutua a largo plazo no está evaluada.',
    stars: Object.freeze(stars),
    planets: Object.freeze(planets),
    moons: Object.freeze(moons),
    minorBodies: Object.freeze(minorBodies),
    asteroidBelts: Object.freeze(belts),
    habitableZone: zones[0] ?? null,
    habitableZones: Object.freeze(zones),
    hostVisualEnvelope: null,
    multistellarPresentation: null,
    multistellarPTypeClearance: null,
    multistellarCoreCompaction: null,
    stellarOrbitClearance: null,
    firstOrbitAnchor: null,
    orbitalRiskTargets: Object.freeze(riskTargets),
    layers: Object.freeze({
      moonCount: moons.length,
      minorBodyCount: minorBodies.length,
      habitableZoneAvailable: zones.length > 0,
      orbitalRiskTargetCount: availableRisks.length,
      orbitalCrossingTargetCount: crossingRisks.length,
      orbitalApproachTargetCount: availableRisks.filter(risk => risk.severity === 'APPROACH').length,
      orbitalCollisionGeometryTargetCount: availableRisks.filter(risk => risk.severity === 'COLLISION_GEOMETRY').length,
    }),
    orbits: Object.freeze(orbits),
    motions: Object.freeze(motions),
    simulation: Object.freeze({
      epochSimulationDay: 0,
      playbackDaysPerRealSecond,
    }),
    scale,
  });

  return composite;
}

function localReferenceRadius(source: SystemSceneSnapshot): number {
  return Math.max(
    0.6,
    ...source.stars.map(star => star.radiusScene * 3.1),
    ...source.planets.map(planet => {
      const orbit = source.orbits.find(candidate => candidate.id === planet.orbitId);
      const motion = source.motions.find(candidate => candidate.id === orbit?.motionId);
      return (orbit?.semiMajorScene ?? 0) * (1 + (motion?.eccentricity ?? 0)) + planet.radiusScene;
    }),
    ...(source.asteroidBelts?.map(belt => belt.outerRadiusScene) ?? []),
    source.habitableZone?.radiativeOuterRadiusScene ?? 0,
  );
}
