import { StellarNeutronStar } from './stellar-neutron-star';

/**
 * 27.5: evidence supplied by a FUTURE verified binary/mass-transfer model.
 * This is NOT generated by 27.5: no companion or accretion history is invented.
 * Ages use the same progenitor-age origin as StellarNeutronStar.
 */
export interface StellarPulsarRecyclingEvidence {
  readonly massTransferConfirmed: true;
  readonly companionIdentity: string;
  readonly recyclingAgeBillionYears: number;
}

export type StellarPulsarKind = 'ORDINARY' | 'MILLISECOND';

/**
 * Read-only, illustrative rotation-powered pulsar candidate. This is internal
 * physical Ground Truth, NOT a detected object or a radio observation. An
 * observer-beam crossing is only a geometrical prerequisite for visibility.
 * A millisecond pulsar requires independent binary-recycling evidence.
 */
export class StellarPulsar {
  static readonly SECONDS_PER_GYR = 31_557_600_000_000_000;
  static readonly REFERENCE_MOMENT_OF_INERTIA_KG_M2 = 1e38;

  readonly spinFrequencyHz: number;
  readonly periodDerivativeSecondsPerSecond: number;
  readonly rotationalEnergyLossWatts: number;
  readonly characteristicSpinDownAgeYears: number;
  readonly beamCrossesLineOfSight: boolean;

  constructor(
    readonly neutronStar: StellarNeutronStar,
    readonly kind: StellarPulsarKind,
    readonly initialSpinPeriodSeconds: number,
    readonly spinPeriodSeconds: number,
    readonly dipolarMagneticFieldTesla: number,
    readonly magneticInclinationDegrees: number,
    readonly observerInclinationDegrees: number,
    readonly beamHalfOpeningAngleDegrees: number,
    readonly recyclingEvidence: StellarPulsarRecyclingEvidence | null,
  ) {
    if (!(neutronStar instanceof StellarNeutronStar)) {
      throw new TypeError('A pulsar requires an existing 27.4 neutron-star profile.');
    }
    if (kind !== 'ORDINARY' && kind !== 'MILLISECOND') {
      throw new RangeError('Unknown 27.5 pulsar kind.');
    }
    if (kind === 'ORDINARY' && recyclingEvidence !== null ||
        kind === 'MILLISECOND' && recyclingEvidence === null) {
      throw new RangeError('Millisecond pulsars require confirmed mass-transfer evidence; ordinary pulsars cannot use it.');
    }
    if (recyclingEvidence !== null) {
      const currentAge = neutronStar.formationAgeBillionYears + neutronStar.ageSinceFormationBillionYears;
      if (recyclingEvidence.massTransferConfirmed !== true ||
          typeof recyclingEvidence.companionIdentity !== 'string' ||
          !/^[A-Za-z0-9:_-]{1,128}$/.test(recyclingEvidence.companionIdentity) ||
          !Number.isFinite(recyclingEvidence.recyclingAgeBillionYears) ||
          recyclingEvidence.recyclingAgeBillionYears < neutronStar.formationAgeBillionYears ||
          recyclingEvidence.recyclingAgeBillionYears > currentAge) {
        throw new RangeError('Recycling evidence must identify a companion and a valid post-remnant mass-transfer epoch.');
      }
      // A shallow copy prevents an external caller mutating the provenance.
      this.recyclingEvidence = Object.freeze({ ...recyclingEvidence });
    }
    const lowerPeriod = kind === 'MILLISECOND' ? 0.002 : 0.04;
    const upperPeriod = kind === 'MILLISECOND' ? 0.03 : 30;
    const lowerField = kind === 'MILLISECOND' ? 1e4 : 1e7;
    const upperField = kind === 'MILLISECOND' ? 1e5 : 3e8;
    if (!Number.isFinite(initialSpinPeriodSeconds) ||
        initialSpinPeriodSeconds < lowerPeriod || initialSpinPeriodSeconds > upperPeriod ||
        !Number.isFinite(spinPeriodSeconds) || spinPeriodSeconds < initialSpinPeriodSeconds ||
        spinPeriodSeconds > upperPeriod || !Number.isFinite(dipolarMagneticFieldTesla) ||
        dipolarMagneticFieldTesla < lowerField || dipolarMagneticFieldTesla > upperField) {
      throw new RangeError('Pulsar spin and dipolar field must be finite and within the kind-specific illustrative envelope.');
    }
    if (![magneticInclinationDegrees, observerInclinationDegrees, beamHalfOpeningAngleDegrees]
        .every(Number.isFinite) || magneticInclinationDegrees < 0 ||
        magneticInclinationDegrees > 90 || observerInclinationDegrees < 0 ||
        observerInclinationDegrees > 180 || beamHalfOpeningAngleDegrees <= 0 ||
        beamHalfOpeningAngleDegrees > 45) {
      throw new RangeError('Pulsar beam geometry requires finite valid angles in degrees.');
    }
    const fieldGauss = dipolarMagneticFieldTesla * 10_000;
    // Vacuum-dipole-inspired B ~ 3.2e19 sqrt(P Pdot) Gauss. Not a measured B/Pdot.
    this.periodDerivativeSecondsPerSecond = (fieldGauss / 3.2e19) ** 2 / spinPeriodSeconds;
    this.spinFrequencyHz = 1 / spinPeriodSeconds;
    this.rotationalEnergyLossWatts = 4 * Math.PI ** 2 *
      StellarPulsar.REFERENCE_MOMENT_OF_INERTIA_KG_M2 *
      this.periodDerivativeSecondsPerSecond / spinPeriodSeconds ** 3;
    this.characteristicSpinDownAgeYears = spinPeriodSeconds /
      (2 * this.periodDerivativeSecondsPerSecond) / (StellarPulsar.SECONDS_PER_GYR / 1e9);
    this.beamCrossesLineOfSight = Math.min(
      Math.abs(observerInclinationDegrees - magneticInclinationDegrees),
      Math.abs(observerInclinationDegrees - (180 - magneticInclinationDegrees)),
    ) <= beamHalfOpeningAngleDegrees;
    if (![this.periodDerivativeSecondsPerSecond, this.spinFrequencyHz,
      this.rotationalEnergyLossWatts, this.characteristicSpinDownAgeYears].every(
      value => Number.isFinite(value) && value > 0,
    )) {
      throw new RangeError('The pulsar spin-derived quantities must be finite and positive.');
    }
    Object.freeze(this);
  }
}
